context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.name = "Default-Output"
            node.description = "Default-Output"
            #node.passive = "false"
            object.linger = "true"
            capture.props = {
                media.class=Audio/Sink
                node.channel-names = [ L R ]
            }
            playback.props = {
                media.class=Stream/Output/Audio
                node.channel-names = [ L R ]
                #target.node="alsa_output.usb-RME_Fireface_UFX_II__23816741__A2718C9963BC0C8-00.pro-output-0"
                #audio.position=[ AUX0 AUX1 ]
                #priority.driver = 2000
                #priority.session = 2000
                node.autoconnect = "true"
            }
        }
    }
]
