jack.properties = {
    rt.prio = 99
    #node.latency = 96/48000
    #node.quantum = 96/48000
    #node.force-quantum  = 96
    #node.lock-quantum = true
    #jack.merge-monitor = false
    jack.show-monitor = false
    jack.short-name = true
    #jack.show-midi = true
}
