monitor.alsa.rules = [
    {
        matches = [
            {
                device.name = "~alsa_card.+RME_Fireface_UFX_II.*"
            }
        ]
        actions = {
            update-props = {
                device.profile = "pro-audio"
                device.profile.pro = true
            }
        }
    }
]



monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "~alsa_output.+RME_Fireface_UFX_II.*"
            }
        ]
        actions = {
            update-props = {
                node.nick = "Fireface_UFXII"
                node.description = "Fireface_UFXII"
                audio.position=[1,2]
                
                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true

                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011

                #node.device-port-name-prefix = "playback"
                node.channel-names = [
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "Phones-1_9",
                    "Phones-1_10",
                    "Phones-2_11",
                    "Phones-2_12",
                    "AES_L",
                    "AES_R",
                    "ADAT_1",
                    "ADAT_2",
                    "ADAT_3",
                    "ADAT_4",
                    "ADAT_5",
                    "ADAT_6",
                    "ADAT_7",
                    "ADAT_8"
                ]
            }
        }
    }
]

monitor.alsa.rules = [
    {
        matches = [
          {
            node.name = "~alsa_input.+RME_Fireface_UFX_II.*"
          }
        ]
        actions = {
            update-props = {
                node.nick = "Fireface_UFXII"
                node.description = "Fireface_UFXII"
                audio.position=[1,2]

                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true
                
                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011
                
                #node.device-port-name-prefix = "capture"
                node.channel-names = [
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "Mic_9",
                    "Mic_10",
                    "Mic_11",
                    "Mic_12",
                    "AES_L",
                    "AES_R",
                    "ADAT_1",
                    "ADAT_2",
                    "ADAT_3",
                    "ADAT_4",
                    "ADAT_5",
                    "ADAT_6",
                    "ADAT_7",
                    "ADAT_8"
                ]
            }
        }
    }
]




