monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "~alsa_output.+M-Audio_FastTrack_Pro.*analog-stereo-a-output"
            },
            {
                node.name = "~alsa_output.+M-Audio_FastTrack_Pro.*pro-output-0"
            }
        ]
        actions = {
            update-props = {
                node.nick = "M-Audio_FastTrack_A"
                node.description = "M-Audio_FastTrack_A"
                audio.position=[1,2]
                
                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true

                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011


                node.device-port-name-prefix = "playback"
            }
        }
    }
]

monitor.alsa.rules = [
    {
        matches = [
            {
            node.name = "~alsa_input.+M-Audio_FastTrack_Pro.*analog-stereo-a-input"
            },
            {
                node.name = "~alsa_input.+M-Audio_FastTrack_Pro.*pro-input-0"
            }
        ]
        actions = {
            update-props = {
                node.nick = "M-Audio_FastTrack_A"
                node.description = "M-Audio_FastTrack_A"
                audio.position=[1,2]
                
                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true
                
                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011
                
                node.device-port-name-prefix = "capture"

            }
        }
    }
]


monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "~alsa_output.+M-Audio_FastTrack_Pro.*analog-stereo-b-output"
            },
            {
                node.name = "~alsa_output.+M-Audio_FastTrack_Pro.*pro-output-1"
            }
        ]
        actions = {
            update-props = {
                node.nick = "M-Audio_FastTrack_B"
                node.description = "M-Audio_FastTrack_B"
                audio.position=[1,2]
                
                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true

                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011


                node.device-port-name-prefix = "playback"
            }
        }
    }
]

monitor.alsa.rules = [
    {
        matches = [
            {
            node.name = "~alsa_input.+M-Audio_FastTrack_Pro.*analog-stereo-b-input"
            },
            {
                node.name = "~alsa_input.+M-Audio_FastTrack_Pro.*pro-input-1"
            }
        ]
        actions = {
            update-props = {
                node.nick = "M-Audio_FastTrack_B"
                node.description = "M-Audio_FastTrack_B"
                audio.position=[1,2]
                
                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true
                
                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011
                
                node.device-port-name-prefix = "capture"

            }
        }
    }
]
