monitor.alsa.rules = [
    {
        matches = [
            {
                device.name = "~alsa_card.+Soundcraft_Soundcraft_Signature_12_MTK.*"
            }
        ]
        actions = {
            update-props = {
                device.profile = "pro-audio"
                device.profile.pro = true
            }
        }
    }
]



monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "~alsa_output.+Soundcraft_Soundcraft_Signature_12_MTK.*"
            }
        ]
        actions = {
            update-props = {
                node.nick = "Signature_12"
                node.description = "Signature_12"
                audio.position=[1,2]
                
                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true

                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011
            }
        }
    }
]

monitor.alsa.rules = [
    {
        matches = [
          {
            node.name = "~alsa_input.+Soundcraft_Soundcraft_Signature_12_MTK.*"
          }
        ]
        actions = {
            update-props = {
                node.nick = "Signature_12"
                node.description = "Signature_12"
                audio.position=[1,2]

                ## Latencia 
                #api.alsa.period-num = 2
                #api.alsa.period-size = 128
                #api.alsa.disable-batch = true
                
                ## Prioridad (Descomenta si lo necesitas)
                # priority.driver = 1011
                # priority.session = 1011
            }
        }
    }
]




