wireplumber.components = [
    {
        name = snd_link_devices.lua,
        type = script/lua,
        provides = custom.snd_link_devices
        arguments = {
            sink = "Default-Output"
        }
    }
]

wireplumber.profiles = {
    main = {
        custom.snd_link_devices = "required"
    }
}